CC = gcc
CXX = g++
FLAGS = -Wall

errors: error1 error3 error4 error5 error6 error7 error8 error9 error10 error11 error12 error13

error1:
	$(CXX) $(FLAGS) error1-2.cpp
error3:
	$(CXX) $(FLAGS) error3.cpp
error4:
	$(CXX) $(FLAGS) error4.cpp
error5:
	$(CXX) $(FLAGS) error5.cpp
error6:
	$(CXX) $(FLAGS) error6.cpp
error7:
	$(CXX) $(FLAGS) error7.cpp
error8:
	$(CXX) $(FLAGS) -library error8.cpp
error9:
	$(CC) $(FLAGS) error9.c
error10:
	$(CXX) $(FLAGS) error10.cpp
error11:
	$(CXX) $(FLAGS) error11.cpp
error12:
	$(CXX) $(FLAGS) error12.cpp
error13:
	$(CXX) $(FLAGS) error13.cpp